<<<<<<< HEAD
# Generated by Django 2.1.5 on 2019-11-24 02:02
=======
# Generated by Django 2.0 on 2019-11-22 16:09
>>>>>>> origin/master

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

=======
    atomic = False
>>>>>>> origin/master
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
=======
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=10)),
>>>>>>> origin/master
            ],
        ),
    ]
