# Generated by Django 2.0 on 2019-11-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
    ]
