# Generated by Django 2.1.5 on 2019-11-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
