# Generated by Django 2.0 on 2019-11-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('firstapp', '0002_auto_20191122_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=20),
        ),
    ]
