# Generated by Django 2.1.5 on 2019-11-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20191123_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='gender',
            field=models.CharField(default='Do not want to share!', max_length=20),
        ),
    ]
