# Generated by Django 2.1.5 on 2019-11-24 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_stu_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Session', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='stu',
            name='gender',
            field=models.CharField(default='Do not want to share', max_length=20),
        ),
        migrations.AddField(
            model_name='stusession',
            name='Session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.TypeOfSession'),
        ),
    ]
