# Generated by Django 2.0 on 2019-11-23 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('firstapp', '0003_auto_20191123_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Python',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Session', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.Python')),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
