# Generated by Django 2.1.5 on 2019-11-23 23:53

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('firstapp', '0004_auto_20191123_1728'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Python',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentDetail',
        ),
    ]
