# Generated by Django 2.1.5 on 2019-11-24 00:01

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('firstapp', '0005_auto_20191123_1753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Python',
        ),
        migrations.RenameModel(
            old_name='StudentDetail',
            new_name='Student',
        ),
    ]
