# Generated by Django 2.1.5 on 2019-11-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_signupform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('pname', models.CharField(max_length=15)),
                ('pemail', models.EmailField(max_length=254)),
                ('blog', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
