# Generated by Django 2.1.5 on 2019-11-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupform',
            name='email',
            field=models.EmailField(default='Email not provied', max_length=254),
        ),
    ]
