# Generated by Django 2.1.5 on 2019-11-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('firstapp', '0006_auto_20191123_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
