# Generated by Django 2.1.5 on 2019-11-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_signupform_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupform',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
