# Generated by Django 2.1.5 on 2019-11-24 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('firstapp', '0008_auto_20191123_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('name', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='firstapp.Student')),
            ],
        ),
        migrations.DeleteModel(
            name='StuInfo',
        ),
    ]
