# Generated by Django 2.1.5 on 2019-11-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('firstapp', '0009_auto_20191123_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='email',
            field=models.EmailField(max_length=20),
        ),
    ]
