# Generated by Django 2.1.5 on 2019-11-24 00:26

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('firstapp', '0010_auto_20191123_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Session',
        ),
        migrations.RemoveField(
            model_name='studentinformation',
            name='name',
        ),
        migrations.DeleteModel(
            name='Python',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentInformation',
        ),
    ]
