# Generated by Django 2.1.5 on 2019-11-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    initial = True

    dependencies = [
        ('firstapp', '0011_auto_20191123_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailofStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
