# Generated by Django 2.1.5 on 2019-11-24 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Session',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.DeleteModel(
            name='DetailofStudent',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
