# Generated by Django 2.1.5 on 2019-11-24 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_auto_20191123_1911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Python',
        ),
    ]
